### create - order
POST http://localhost:8000/order-service/0018ed0f-67f0-4c5d-8b81-4adb8a9fa55b/orders
Content-Type: application/json

{
  "productId": "CATALOG-001",
  "qty": 10,
  "unitPrice": 1500
}

### get - orders(userId)
GET http://localhost:8000/order-service/802880b0-d1d4-4875-a7aa-31c84f1b2aba/orders
content-type: application/json