### create User
POST http://localhost:8000/user-service/users
Content-Type: application/json

{
  "name": "pilhwan",
  "email": "aaa1@naver.com",
  "pwd": "abcd1234"
}

### get Users
GET http://localhost:8000/user-service/users
Content-Type: application/json

### get User
GET http://localhost:8000/user-service/users/bf05bf92-5645-42a1-9e82-eaeaa9457418
Content-Type: application/json
